// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"time"
)

type Device struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Uid       string    `json:"uid"`
	Caption   string    `json:"caption"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type EpisodeAction struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	DeviceID   *int64    `json:"device_id"`
	PodcastUrl string    `json:"podcast_url"`
	EpisodeUrl string    `json:"episode_url"`
	Action     string    `json:"action"`
	Timestamp  time.Time `json:"timestamp"`
	Started    *int64    `json:"started"`
	Position   *int64    `json:"position"`
	Total      *int64    `json:"total"`
	CreatedAt  time.Time `json:"created_at"`
}

type Podcast struct {
	ID            int64     `json:"id"`
	Url           string    `json:"url"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Author        string    `json:"author"`
	SiteUrl       string    `json:"site_url"`
	ImageUrl      string    `json:"image_url"`
	Etag          string    `json:"etag"`
	LastModified  string    `json:"last_modified"`
	LastFetchedAt time.Time `json:"last_fetched_at"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type PodcastEpisode struct {
	ID              int64     `json:"id"`
	PodcastID       int64     `json:"podcast_id"`
	EpisodeUrl      string    `json:"episode_url"`
	Guid            string    `json:"guid"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	PublishedAt     time.Time `json:"published_at"`
	DurationSeconds *int64    `json:"duration_seconds"`
	MimeType        string    `json:"mime_type"`
	ByteSize        *int64    `json:"byte_size"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Setting struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
}

type Subscription struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	DeviceID   int64     `json:"device_id"`
	PodcastUrl string    `json:"podcast_url"`
	CreatedAt  time.Time `json:"created_at"`
}

type SubscriptionEvent struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	DeviceID   int64     `json:"device_id"`
	PodcastUrl string    `json:"podcast_url"`
	Action     string    `json:"action"`
	CreatedAt  time.Time `json:"created_at"`
}

type SyncGroup struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type SyncGroupMember struct {
	DeviceID    int64 `json:"device_id"`
	SyncGroupID int64 `json:"sync_group_id"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
