// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlite

import (
	"context"
	"strings"
	"time"
)

const countSubscriptions = `-- name: CountSubscriptions :one
SELECT COUNT(*) FROM subscriptions WHERE user_id = ? AND device_id = ?
`

type CountSubscriptionsParams struct {
	UserID   int64 `json:"user_id"`
	DeviceID int64 `json:"device_id"`
}

func (q *Queries) CountSubscriptions(ctx context.Context, arg CountSubscriptionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptions, arg.UserID, arg.DeviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at) VALUES (?, ?, ?)
RETURNING id, user_id, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSyncGroup = `-- name: CreateSyncGroup :one
INSERT INTO sync_groups (user_id) VALUES (?) RETURNING id
`

func (q *Queries) CreateSyncGroup(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSyncGroup, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash) VALUES (?, ?) RETURNING id, username, password_hash, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeviceFromSyncGroups = `-- name: DeleteDeviceFromSyncGroups :exec
DELETE FROM sync_group_members WHERE device_id = ?
`

func (q *Queries) DeleteDeviceFromSyncGroups(ctx context.Context, deviceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceFromSyncGroups, deviceID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE user_id = ? AND scope_type = ? AND scope_id = ? AND key = ?
`

type DeleteSettingParams struct {
	UserID    int64  `json:"user_id"`
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	Key       string `json:"key"`
}

func (q *Queries) DeleteSetting(ctx context.Context, arg DeleteSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteSetting,
		arg.UserID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Key,
	)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE user_id = ? AND device_id = ? AND podcast_url = ?
`

type DeleteSubscriptionParams struct {
	UserID     int64  `json:"user_id"`
	DeviceID   int64  `json:"device_id"`
	PodcastUrl string `json:"podcast_url"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, arg.UserID, arg.DeviceID, arg.PodcastUrl)
	return err
}

const deleteSyncGroupMembersByGroupIDs = `-- name: DeleteSyncGroupMembersByGroupIDs :exec
DELETE FROM sync_group_members WHERE sync_group_id IN (/*SLICE:group_ids*/?)
`

func (q *Queries) DeleteSyncGroupMembersByGroupIDs(ctx context.Context, groupIds []int64) error {
	query := deleteSyncGroupMembersByGroupIDs
	var queryParams []interface{}
	if len(groupIds) > 0 {
		for _, v := range groupIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:group_ids*/?", strings.Repeat(",?", len(groupIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:group_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteSyncGroupsByIDs = `-- name: DeleteSyncGroupsByIDs :exec
DELETE FROM sync_groups WHERE user_id = ? AND id IN (/*SLICE:group_ids*/?)
`

type DeleteSyncGroupsByIDsParams struct {
	UserID   int64   `json:"user_id"`
	GroupIds []int64 `json:"group_ids"`
}

func (q *Queries) DeleteSyncGroupsByIDs(ctx context.Context, arg DeleteSyncGroupsByIDsParams) error {
	query := deleteSyncGroupsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.GroupIds) > 0 {
		for _, v := range arg.GroupIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:group_ids*/?", strings.Repeat(",?", len(arg.GroupIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:group_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const findSmallSyncGroups = `-- name: FindSmallSyncGroups :many
SELECT sg.id
FROM sync_groups sg
LEFT JOIN sync_group_members sgm ON sgm.sync_group_id = sg.id
WHERE sg.user_id = ?
GROUP BY sg.id
HAVING COUNT(sgm.device_id) < 2
`

func (q *Queries) FindSmallSyncGroups(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, findSmallSyncGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAggregatedSubscriptions = `-- name: GetAggregatedSubscriptions :many
SELECT sub.podcast_url, COALESCE(p.title, '') AS podcast_title, json_group_array(d.uid) AS devices
FROM subscriptions sub
JOIN devices d ON d.id = sub.device_id
LEFT JOIN podcasts p ON p.url = sub.podcast_url
WHERE sub.user_id = ?
GROUP BY sub.podcast_url, p.title
ORDER BY sub.podcast_url
`

type GetAggregatedSubscriptionsRow struct {
	PodcastUrl   string      `json:"podcast_url"`
	PodcastTitle string      `json:"podcast_title"`
	Devices      interface{} `json:"devices"`
}

func (q *Queries) GetAggregatedSubscriptions(ctx context.Context, userID int64) ([]GetAggregatedSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAggregatedSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAggregatedSubscriptionsRow
	for rows.Next() {
		var i GetAggregatedSubscriptionsRow
		if err := rows.Scan(&i.PodcastUrl, &i.PodcastTitle, &i.Devices); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentSubscriptions = `-- name: GetCurrentSubscriptions :many
SELECT podcast_url FROM subscriptions WHERE user_id = ? AND device_id = ? ORDER BY podcast_url
`

type GetCurrentSubscriptionsParams struct {
	UserID   int64 `json:"user_id"`
	DeviceID int64 `json:"device_id"`
}

func (q *Queries) GetCurrentSubscriptions(ctx context.Context, arg GetCurrentSubscriptionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentSubscriptions, arg.UserID, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var podcast_url string
		if err := rows.Scan(&podcast_url); err != nil {
			return nil, err
		}
		items = append(items, podcast_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT
    (SELECT count(DISTINCT podcast_url) FROM subscriptions WHERE subscriptions.user_id = ?1) AS subscription_count,
    (SELECT count(*) FROM devices WHERE devices.user_id = ?1) AS device_count,
    (SELECT count(*) FROM episode_actions WHERE episode_actions.user_id = ?1) AS episode_action_count
`

type GetDashboardSummaryRow struct {
	SubscriptionCount  int64 `json:"subscription_count"`
	DeviceCount        int64 `json:"device_count"`
	EpisodeActionCount int64 `json:"episode_action_count"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context, userID int64) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardSummary, userID)
	var i GetDashboardSummaryRow
	err := row.Scan(&i.SubscriptionCount, &i.DeviceCount, &i.EpisodeActionCount)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, uid, caption, type, created_at, updated_at FROM devices WHERE user_id = ? AND uid = ?
`

type GetDeviceParams struct {
	UserID int64  `json:"user_id"`
	Uid    string `json:"uid"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, arg.UserID, arg.Uid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uid,
		&i.Caption,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, uid, caption, type, created_at, updated_at FROM devices WHERE id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uid,
		&i.Caption,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceIDByUID = `-- name: GetDeviceIDByUID :one
SELECT id FROM devices WHERE user_id = ? AND uid = ?
`

type GetDeviceIDByUIDParams struct {
	UserID int64  `json:"user_id"`
	Uid    string `json:"uid"`
}

func (q *Queries) GetDeviceIDByUID(ctx context.Context, arg GetDeviceIDByUIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDeviceIDByUID, arg.UserID, arg.Uid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDeviceSyncGroupMemberships = `-- name: GetDeviceSyncGroupMemberships :many
SELECT d.uid, sgm.sync_group_id
FROM sync_group_members sgm
JOIN devices d ON d.id = sgm.device_id
WHERE d.user_id = ?
ORDER BY sgm.sync_group_id, d.uid
`

type GetDeviceSyncGroupMembershipsRow struct {
	Uid         string `json:"uid"`
	SyncGroupID int64  `json:"sync_group_id"`
}

func (q *Queries) GetDeviceSyncGroupMemberships(ctx context.Context, userID int64) ([]GetDeviceSyncGroupMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceSyncGroupMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeviceSyncGroupMembershipsRow
	for rows.Next() {
		var i GetDeviceSyncGroupMembershipsRow
		if err := rows.Scan(&i.Uid, &i.SyncGroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevicesWithSubCount = `-- name: GetDevicesWithSubCount :many
SELECT d.uid, d.caption, d.type,
       (SELECT count(*) FROM subscriptions WHERE device_id = d.id) AS subscription_count,
       d.created_at, d.updated_at
FROM devices d
WHERE d.user_id = ?
ORDER BY d.uid
`

type GetDevicesWithSubCountRow struct {
	Uid               string    `json:"uid"`
	Caption           string    `json:"caption"`
	Type              string    `json:"type"`
	SubscriptionCount int64     `json:"subscription_count"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) GetDevicesWithSubCount(ctx context.Context, userID int64) ([]GetDevicesWithSubCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getDevicesWithSubCount, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDevicesWithSubCountRow
	for rows.Next() {
		var i GetDevicesWithSubCountRow
		if err := rows.Scan(
			&i.Uid,
			&i.Caption,
			&i.Type,
			&i.SubscriptionCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisodeActionsSince = `-- name: GetEpisodeActionsSince :many
SELECT id, user_id, device_id, podcast_url, episode_url, action, timestamp, started, position, total, created_at
FROM episode_actions 
WHERE user_id = ? 
  AND (?2 IS NULL OR created_at >= ?2)
  AND (?3 IS NULL OR podcast_url = ?3)
  AND (?4 IS NULL OR device_id = ?4)
ORDER BY created_at ASC
LIMIT ?5
`

type GetEpisodeActionsSinceParams struct {
	UserID           int64       `json:"user_id"`
	CreatedAfter     interface{} `json:"created_after"`
	PodcastUrlFilter interface{} `json:"podcast_url_filter"`
	DeviceIDFilter   interface{} `json:"device_id_filter"`
	LimitVal         *int64      `json:"limit_val"`
}

func (q *Queries) GetEpisodeActionsSince(ctx context.Context, arg GetEpisodeActionsSinceParams) ([]EpisodeAction, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodeActionsSince,
		arg.UserID,
		arg.CreatedAfter,
		arg.PodcastUrlFilter,
		arg.DeviceIDFilter,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeAction
	for rows.Next() {
		var i EpisodeAction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.PodcastUrl,
			&i.EpisodeUrl,
			&i.Action,
			&i.Timestamp,
			&i.Started,
			&i.Position,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaybackHistory = `-- name: GetPlaybackHistory :many
WITH ranked AS (
    SELECT
        ea.podcast_url,
        ea.episode_url,
        ea.device_id,
        ea.timestamp,
        ea.position,
        ea.total,
        ea.created_at,
        ea.id,
        row_number() OVER (
            PARTITION BY ea.podcast_url, ea.episode_url
            ORDER BY ea.timestamp DESC, ea.created_at DESC, ea.id DESC
        ) AS rn
    FROM episode_actions ea
    WHERE ea.user_id = ?
           AND ea.action = 'play'
)
SELECT ranked.podcast_url,
       COALESCE(p.title, '') AS podcast_title,
       ranked.episode_url,
       COALESCE(pe.title, '') AS episode_title,
       ranked.device_id,
       ranked.timestamp,
       ranked.position,
       ranked.total
FROM ranked
LEFT JOIN podcasts p ON p.url = ranked.podcast_url
LEFT JOIN podcast_episodes pe ON pe.podcast_id = p.id AND pe.episode_url = ranked.episode_url
WHERE rn = 1
ORDER BY ranked.timestamp DESC, ranked.created_at DESC, ranked.id DESC
LIMIT ?
`

type GetPlaybackHistoryParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
}

type GetPlaybackHistoryRow struct {
	PodcastUrl   string    `json:"podcast_url"`
	PodcastTitle string    `json:"podcast_title"`
	EpisodeUrl   string    `json:"episode_url"`
	EpisodeTitle string    `json:"episode_title"`
	DeviceID     *int64    `json:"device_id"`
	Timestamp    time.Time `json:"timestamp"`
	Position     *int64    `json:"position"`
	Total        *int64    `json:"total"`
}

func (q *Queries) GetPlaybackHistory(ctx context.Context, arg GetPlaybackHistoryParams) ([]GetPlaybackHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaybackHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlaybackHistoryRow
	for rows.Next() {
		var i GetPlaybackHistoryRow
		if err := rows.Scan(
			&i.PodcastUrl,
			&i.PodcastTitle,
			&i.EpisodeUrl,
			&i.EpisodeTitle,
			&i.DeviceID,
			&i.Timestamp,
			&i.Position,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPodcastByURL = `-- name: GetPodcastByURL :one
SELECT id, url, title, description, author, site_url, image_url,
       etag, last_modified, last_fetched_at, created_at, updated_at
FROM podcasts
WHERE url = ?
`

func (q *Queries) GetPodcastByURL(ctx context.Context, url string) (Podcast, error) {
	row := q.db.QueryRowContext(ctx, getPodcastByURL, url)
	var i Podcast
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Author,
		&i.SiteUrl,
		&i.ImageUrl,
		&i.Etag,
		&i.LastModified,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentEpisodeActions = `-- name: GetRecentEpisodeActions :many
SELECT ea.id, ea.user_id, ea.device_id, ea.podcast_url, COALESCE(p.title, '') AS podcast_title,
       ea.episode_url, COALESCE(pe.title, '') AS episode_title,
       ea.action, ea.timestamp, ea.started, ea.position, ea.total, ea.created_at
FROM episode_actions ea
LEFT JOIN podcasts p ON p.url = ea.podcast_url
LEFT JOIN podcast_episodes pe ON pe.podcast_id = p.id AND pe.episode_url = ea.episode_url
WHERE ea.user_id = ?
ORDER BY ea.timestamp DESC
LIMIT ?
`

type GetRecentEpisodeActionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
}

type GetRecentEpisodeActionsRow struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	DeviceID     *int64    `json:"device_id"`
	PodcastUrl   string    `json:"podcast_url"`
	PodcastTitle string    `json:"podcast_title"`
	EpisodeUrl   string    `json:"episode_url"`
	EpisodeTitle string    `json:"episode_title"`
	Action       string    `json:"action"`
	Timestamp    time.Time `json:"timestamp"`
	Started      *int64    `json:"started"`
	Position     *int64    `json:"position"`
	Total        *int64    `json:"total"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetRecentEpisodeActions(ctx context.Context, arg GetRecentEpisodeActionsParams) ([]GetRecentEpisodeActionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEpisodeActions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentEpisodeActionsRow
	for rows.Next() {
		var i GetRecentEpisodeActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.PodcastUrl,
			&i.PodcastTitle,
			&i.EpisodeUrl,
			&i.EpisodeTitle,
			&i.Action,
			&i.Timestamp,
			&i.Started,
			&i.Position,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, expires_at, created_at, updated_at
FROM sessions WHERE id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :many
SELECT key, value FROM settings WHERE user_id = ? AND scope_type = ? AND scope_id = ?
`

type GetSettingsParams struct {
	UserID    int64  `json:"user_id"`
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
}

type GetSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetSettings(ctx context.Context, arg GetSettingsParams) ([]GetSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSettings, arg.UserID, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSettingsRow
	for rows.Next() {
		var i GetSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionEventsSince = `-- name: GetSubscriptionEventsSince :many
SELECT id, user_id, device_id, podcast_url, action, created_at
FROM subscription_events
WHERE user_id = ? AND device_id = ? AND created_at >= ?
ORDER BY created_at ASC
`

type GetSubscriptionEventsSinceParams struct {
	UserID    int64     `json:"user_id"`
	DeviceID  int64     `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetSubscriptionEventsSince(ctx context.Context, arg GetSubscriptionEventsSinceParams) ([]SubscriptionEvent, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionEventsSince, arg.UserID, arg.DeviceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionEvent
	for rows.Next() {
		var i SubscriptionEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.PodcastUrl,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsSince = `-- name: GetSubscriptionsSince :many
WITH ranked AS (
    SELECT podcast_url, action,
           ROW_NUMBER() OVER (PARTITION BY podcast_url ORDER BY created_at DESC, id DESC) AS rn
    FROM subscription_events
    WHERE user_id = ? AND device_id = ? AND created_at >= ?
)
SELECT podcast_url, action
FROM ranked
WHERE rn = 1
ORDER BY podcast_url
`

type GetSubscriptionsSinceParams struct {
	UserID    int64     `json:"user_id"`
	DeviceID  int64     `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetSubscriptionsSinceRow struct {
	PodcastUrl string `json:"podcast_url"`
	Action     string `json:"action"`
}

func (q *Queries) GetSubscriptionsSince(ctx context.Context, arg GetSubscriptionsSinceParams) ([]GetSubscriptionsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsSince, arg.UserID, arg.DeviceID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriptionsSinceRow
	for rows.Next() {
		var i GetSubscriptionsSinceRow
		if err := rows.Scan(&i.PodcastUrl, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncGroupSubscriptions = `-- name: GetSyncGroupSubscriptions :many
SELECT DISTINCT podcast_url
FROM subscriptions
WHERE user_id = ? AND device_id IN (/*SLICE:device_ids*/?)
ORDER BY podcast_url
`

type GetSyncGroupSubscriptionsParams struct {
	UserID    int64   `json:"user_id"`
	DeviceIds []int64 `json:"device_ids"`
}

func (q *Queries) GetSyncGroupSubscriptions(ctx context.Context, arg GetSyncGroupSubscriptionsParams) ([]string, error) {
	query := getSyncGroupSubscriptions
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.DeviceIds) > 0 {
		for _, v := range arg.DeviceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:device_ids*/?", strings.Repeat(",?", len(arg.DeviceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:device_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var podcast_url string
		if err := rows.Scan(&podcast_url); err != nil {
			return nil, err
		}
		items = append(items, podcast_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncTargetDeviceIDs = `-- name: GetSyncTargetDeviceIDs :many
SELECT peer.id
FROM devices base
JOIN sync_group_members base_member ON base_member.device_id = base.id
JOIN sync_group_members peer_member ON peer_member.sync_group_id = base_member.sync_group_id
JOIN devices peer ON peer.id = peer_member.device_id
WHERE base.user_id = ? AND base.id = ?
ORDER BY peer.id
`

type GetSyncTargetDeviceIDsParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetSyncTargetDeviceIDs(ctx context.Context, arg GetSyncTargetDeviceIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getSyncTargetDeviceIDs, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBySessionID = `-- name: GetUserBySessionID :one
SELECT u.id, u.username, u.password_hash, u.created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = ? AND s.expires_at > ?
`

type GetUserBySessionIDParams struct {
	ID        string    `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetUserBySessionID(ctx context.Context, arg GetUserBySessionIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySessionID, arg.ID, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertEpisodeAction = `-- name: InsertEpisodeAction :exec
INSERT INTO episode_actions (user_id, device_id, podcast_url, episode_url, action, timestamp, started, position, total, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEpisodeActionParams struct {
	UserID     int64     `json:"user_id"`
	DeviceID   *int64    `json:"device_id"`
	PodcastUrl string    `json:"podcast_url"`
	EpisodeUrl string    `json:"episode_url"`
	Action     string    `json:"action"`
	Timestamp  time.Time `json:"timestamp"`
	Started    *int64    `json:"started"`
	Position   *int64    `json:"position"`
	Total      *int64    `json:"total"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) InsertEpisodeAction(ctx context.Context, arg InsertEpisodeActionParams) error {
	_, err := q.db.ExecContext(ctx, insertEpisodeAction,
		arg.UserID,
		arg.DeviceID,
		arg.PodcastUrl,
		arg.EpisodeUrl,
		arg.Action,
		arg.Timestamp,
		arg.Started,
		arg.Position,
		arg.Total,
		arg.CreatedAt,
	)
	return err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO subscriptions (user_id, device_id, podcast_url) VALUES (?, ?, ?)
ON CONFLICT (user_id, device_id, podcast_url) DO NOTHING
`

type InsertSubscriptionParams struct {
	UserID     int64  `json:"user_id"`
	DeviceID   int64  `json:"device_id"`
	PodcastUrl string `json:"podcast_url"`
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertSubscription, arg.UserID, arg.DeviceID, arg.PodcastUrl)
	return err
}

const insertSubscriptionEvent = `-- name: InsertSubscriptionEvent :exec
INSERT INTO subscription_events (user_id, device_id, podcast_url, action, created_at) VALUES (?, ?, ?, ?, ?)
`

type InsertSubscriptionEventParams struct {
	UserID     int64     `json:"user_id"`
	DeviceID   int64     `json:"device_id"`
	PodcastUrl string    `json:"podcast_url"`
	Action     string    `json:"action"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) InsertSubscriptionEvent(ctx context.Context, arg InsertSubscriptionEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSubscriptionEvent,
		arg.UserID,
		arg.DeviceID,
		arg.PodcastUrl,
		arg.Action,
		arg.CreatedAt,
	)
	return err
}

const insertSyncGroupMember = `-- name: InsertSyncGroupMember :exec
INSERT INTO sync_group_members (device_id, sync_group_id) VALUES (?, ?)
`

type InsertSyncGroupMemberParams struct {
	DeviceID    int64 `json:"device_id"`
	SyncGroupID int64 `json:"sync_group_id"`
}

func (q *Queries) InsertSyncGroupMember(ctx context.Context, arg InsertSyncGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertSyncGroupMember, arg.DeviceID, arg.SyncGroupID)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT id, user_id, uid, caption, type, created_at, updated_at FROM devices WHERE user_id = ? ORDER BY uid
`

func (q *Queries) ListDevices(ctx context.Context, userID int64) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Uid,
			&i.Caption,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const podcastEpisodeExists = `-- name: PodcastEpisodeExists :one
SELECT EXISTS (
    SELECT 1
    FROM podcast_episodes pe
    JOIN podcasts p ON p.id = pe.podcast_id
    WHERE p.url = ? AND pe.episode_url = ?
)
`

type PodcastEpisodeExistsParams struct {
	Url        string `json:"url"`
	EpisodeUrl string `json:"episode_url"`
}

func (q *Queries) PodcastEpisodeExists(ctx context.Context, arg PodcastEpisodeExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, podcastEpisodeExists, arg.Url, arg.EpisodeUrl)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (user_id, scope_type, scope_id, key, value) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id, scope_type, scope_id, key) DO UPDATE SET value = EXCLUDED.value
`

type SetSettingParams struct {
	UserID    int64  `json:"user_id"`
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting,
		arg.UserID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Key,
		arg.Value,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET expires_at = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type TouchSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        string    `json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE devices SET caption = ?, type = ?, updated_at = CURRENT_TIMESTAMP WHERE user_id = ? AND uid = ?
`

type UpdateDeviceParams struct {
	Caption string `json:"caption"`
	Type    string `json:"type"`
	UserID  int64  `json:"user_id"`
	Uid     string `json:"uid"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, updateDevice,
		arg.Caption,
		arg.Type,
		arg.UserID,
		arg.Uid,
	)
	return err
}

const updatePodcastFetchState = `-- name: UpdatePodcastFetchState :exec
UPDATE podcasts
SET etag = ?,
    last_modified = ?,
    last_fetched_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE url = ?
`

type UpdatePodcastFetchStateParams struct {
	Etag          string    `json:"etag"`
	LastModified  string    `json:"last_modified"`
	LastFetchedAt time.Time `json:"last_fetched_at"`
	Url           string    `json:"url"`
}

func (q *Queries) UpdatePodcastFetchState(ctx context.Context, arg UpdatePodcastFetchStateParams) error {
	_, err := q.db.ExecContext(ctx, updatePodcastFetchState,
		arg.Etag,
		arg.LastModified,
		arg.LastFetchedAt,
		arg.Url,
	)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (user_id, uid) VALUES (?, ?)
ON CONFLICT (user_id, uid) DO UPDATE SET updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, uid, caption, type, created_at, updated_at
`

type UpsertDeviceParams struct {
	UserID int64  `json:"user_id"`
	Uid    string `json:"uid"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, upsertDevice, arg.UserID, arg.Uid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uid,
		&i.Caption,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPodcastEpisode = `-- name: UpsertPodcastEpisode :exec
INSERT INTO podcast_episodes (
    podcast_id, episode_url, guid, title, description,
    published_at, duration_seconds, mime_type, byte_size
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (podcast_id, episode_url) DO UPDATE SET
    guid = EXCLUDED.guid,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    published_at = EXCLUDED.published_at,
    duration_seconds = EXCLUDED.duration_seconds,
    mime_type = EXCLUDED.mime_type,
    byte_size = EXCLUDED.byte_size,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPodcastEpisodeParams struct {
	PodcastID       int64     `json:"podcast_id"`
	EpisodeUrl      string    `json:"episode_url"`
	Guid            string    `json:"guid"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	PublishedAt     time.Time `json:"published_at"`
	DurationSeconds *int64    `json:"duration_seconds"`
	MimeType        string    `json:"mime_type"`
	ByteSize        *int64    `json:"byte_size"`
}

func (q *Queries) UpsertPodcastEpisode(ctx context.Context, arg UpsertPodcastEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertPodcastEpisode,
		arg.PodcastID,
		arg.EpisodeUrl,
		arg.Guid,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.DurationSeconds,
		arg.MimeType,
		arg.ByteSize,
	)
	return err
}

const upsertPodcastMetadata = `-- name: UpsertPodcastMetadata :one
INSERT INTO podcasts (
    url, title, description, author, site_url, image_url,
    etag, last_modified, last_fetched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (url) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    author = EXCLUDED.author,
    site_url = EXCLUDED.site_url,
    image_url = EXCLUDED.image_url,
    etag = EXCLUDED.etag,
    last_modified = EXCLUDED.last_modified,
    last_fetched_at = EXCLUDED.last_fetched_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type UpsertPodcastMetadataParams struct {
	Url           string    `json:"url"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Author        string    `json:"author"`
	SiteUrl       string    `json:"site_url"`
	ImageUrl      string    `json:"image_url"`
	Etag          string    `json:"etag"`
	LastModified  string    `json:"last_modified"`
	LastFetchedAt time.Time `json:"last_fetched_at"`
}

func (q *Queries) UpsertPodcastMetadata(ctx context.Context, arg UpsertPodcastMetadataParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertPodcastMetadata,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.SiteUrl,
		arg.ImageUrl,
		arg.Etag,
		arg.LastModified,
		arg.LastFetchedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
