// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"time"
)

type Querier interface {
	CountSubscriptions(ctx context.Context, arg CountSubscriptionsParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSyncGroup(ctx context.Context, userID int64) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDeviceFromSyncGroups(ctx context.Context, deviceID int64) error
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSetting(ctx context.Context, arg DeleteSettingParams) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error
	DeleteSyncGroupMembersByGroupIDs(ctx context.Context, groupIds []int64) error
	DeleteSyncGroupsByIDs(ctx context.Context, arg DeleteSyncGroupsByIDsParams) error
	FindSmallSyncGroups(ctx context.Context, userID int64) ([]int64, error)
	GetAggregatedSubscriptions(ctx context.Context, userID int64) ([]GetAggregatedSubscriptionsRow, error)
	GetCurrentSubscriptions(ctx context.Context, arg GetCurrentSubscriptionsParams) ([]string, error)
	GetDashboardSummary(ctx context.Context, userID int64) (GetDashboardSummaryRow, error)
	GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error)
	GetDeviceByID(ctx context.Context, id int64) (Device, error)
	GetDeviceIDByUID(ctx context.Context, arg GetDeviceIDByUIDParams) (int64, error)
	GetDeviceSyncGroupMemberships(ctx context.Context, userID int64) ([]GetDeviceSyncGroupMembershipsRow, error)
	GetDevicesWithSubCount(ctx context.Context, userID int64) ([]GetDevicesWithSubCountRow, error)
	GetEpisodeActionsSince(ctx context.Context, arg GetEpisodeActionsSinceParams) ([]EpisodeAction, error)
	GetPlaybackHistory(ctx context.Context, arg GetPlaybackHistoryParams) ([]GetPlaybackHistoryRow, error)
	GetPodcastByURL(ctx context.Context, url string) (Podcast, error)
	GetRecentEpisodeActions(ctx context.Context, arg GetRecentEpisodeActionsParams) ([]GetRecentEpisodeActionsRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSettings(ctx context.Context, arg GetSettingsParams) ([]GetSettingsRow, error)
	GetSubscriptionEventsSince(ctx context.Context, arg GetSubscriptionEventsSinceParams) ([]SubscriptionEvent, error)
	GetSubscriptionsSince(ctx context.Context, arg GetSubscriptionsSinceParams) ([]GetSubscriptionsSinceRow, error)
	GetSyncGroupSubscriptions(ctx context.Context, arg GetSyncGroupSubscriptionsParams) ([]string, error)
	GetSyncTargetDeviceIDs(ctx context.Context, arg GetSyncTargetDeviceIDsParams) ([]int64, error)
	GetUserBySessionID(ctx context.Context, arg GetUserBySessionIDParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertEpisodeAction(ctx context.Context, arg InsertEpisodeActionParams) error
	InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error
	InsertSubscriptionEvent(ctx context.Context, arg InsertSubscriptionEventParams) error
	InsertSyncGroupMember(ctx context.Context, arg InsertSyncGroupMemberParams) error
	ListDevices(ctx context.Context, userID int64) ([]Device, error)
	PodcastEpisodeExists(ctx context.Context, arg PodcastEpisodeExistsParams) (bool, error)
	SetSetting(ctx context.Context, arg SetSettingParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error
	UpdatePodcastFetchState(ctx context.Context, arg UpdatePodcastFetchStateParams) error
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	UpsertPodcastEpisode(ctx context.Context, arg UpsertPodcastEpisodeParams) error
	UpsertPodcastMetadata(ctx context.Context, arg UpsertPodcastMetadataParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
